python train.py --task=ada11 --headless --max_iterations=1200
python train.py --task=ada12 --headless --max_iterations=1200
python train.py --task=ada14 --headless --max_iterations=1200
python train.py --task=ada21 --headless --max_iterations=1200
python train.py --task=ada24 --headless --max_iterations=1200
python train.py --task=dpme11 --headless --max_iterations=1200
python train.py --task=dpme12 --headless --max_iterations=1200
python train.py --task=dpme14 --headless --max_iterations=1200
python train.py --task=dpme21 --headless --max_iterations=1200
python train.py --task=dpme24 --headless --max_iterations=1200
python train.py --task=nmi11 --headless --max_iterations=1200
python train.py --task=nmi12 --headless --max_iterations=1200
python train.py --task=nmi14 --headless --max_iterations=1200
python train.py --task=dpmf11 --headless --max_iterations=1200
python train.py --task=dpmf12 --headless --max_iterations=1200
python train.py --task=dpmf14 --headless --max_iterations=1200
python train.py --task=dpmf21 --headless --max_iterations=1200
python train.py --task=dpmf24 --headless --max_iterations=1200
python train.py --task=dpmt11 --headless --max_iterations=1200
python train.py --task=dpmt12 --headless --max_iterations=1200
python train.py --task=dpmt14 --headless --max_iterations=1200
python train.py --task=dpmt21 --headless --max_iterations=1200
python train.py --task=dpmt24 --headless --max_iterations=1200
